# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
    - job: FirstJob
      steps:
      - bash: echo Build FirstJob
      - bash: echo $(PiplelineLevelVariable)
    - job: SecondJob
      steps:
      - bash: echo Build SecondJob

- stage: DevDeploy
  variables:
    environment: Dev
  dependsOn: Build
  jobs:
    - job: DevDeploy
      steps:
      - bash: echo $(environment)Deploy

- stage: QADeploy
  variables:
    environment: QA
  dependsOn: Build
  jobs:
    - job: QADeploy
      steps:
      - bash: echo $(environment)Deploy

- stage: StageDeploy
  variables:
    environment: Stage
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs:
    - job: StageDeploy
      steps:
      - bash: echo $(environment)Deploy

- stage: ProdDeploy
  variables:
    environment: Prod
  jobs:
    - job: ProdDeploy
      steps:
      - bash: echo $(environment)Deploy